//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aok_Patch.patcher_.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Aok_Patch.patcher_.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] AoC_10 {
            get {
                object obj = ResourceManager.GetObject("AoC_10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] AoC_10ce {
            get {
                object obj = ResourceManager.GetObject("AoC_10ce", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à JASC-PAL
        ///0100
        ///256
        ///0 0 0
        ///0 74 161
        ///0 97 155
        ///0 74 187
        ///0 84 176
        ///0 90 184
        ///0 110 176
        ///0 110 187
        ///180 255 180
        ///0 98 210
        ///0 0 0
        ///47 47 47
        ///200 216 255
        ///87 87 87
        ///37 16 6
        ///47 26 17
        ///0 0 82
        ///0 21 130
        ///19 49 161
        ///48 93 182
        ///74 121 208
        ///110 166 235
        ///151 206 255
        ///205 250 255
        ///64 43 23
        ///67 51 27
        ///70 32 6
        ///75 57 42
        ///84 64 43
        ///87 69 37
        ///87 57 27
        ///94 74 48
        ///65 0 0
        ///105 11 0
        ///160 21 0
        ///230 11 0
        ///255 0 0
        ///255 100 100
        ///255 160 160
        ///255 220 220
        ///97 77 67
        ///103 58 21
        ///113 75 51
        ///113 75 13
        ///115 105 84
        ///125 97 72
        ///125 74 0 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string AOE2_Alpha_l {
            get {
                return ResourceManager.GetString("AOE2_Alpha_l", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] AoK_20 {
            get {
                object obj = ResourceManager.GetObject("AoK_20", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] AoK_20a {
            get {
                object obj = ResourceManager.GetObject("AoK_20a", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] AoK_20b {
            get {
                object obj = ResourceManager.GetObject("AoK_20b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] AoK_20bis {
            get {
                object obj = ResourceManager.GetObject("AoK_20bis", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localisée de type System.Byte[].
        /// </summary>
        internal static byte[] wndmode {
            get {
                object obj = ResourceManager.GetObject("wndmode", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
