// resizeframes.globals.c
// Generated by decompiling resizeframes.exe
// using Reko decompiler version 0.9.0.0.

#include "resizeframes.h"

Eq_5375 g_tFFFFFFFC;
Eq_1056 g_tFFFFFFFF;
Eq_707 g_t0001;
<anonymous> g_t4011DC = <code>;
<anonymous> g_t402DA0 = <code>;
byte g_b4031DC = 0x20;
struct Eq_2674 * g_ptr406B54 = &g_t406B58;
struct Eq_707 * g_ptr407178 = &g_t4071C4;
<anonymous> * g_a408491[] = 
	{
	};
struct Eq_707 * g_ptr413404 = &g_t413450;
struct Eq_707 * g_ptr4134BC = &g_t413508;
struct Eq_707 * g_ptr413518 = &g_t413564;
struct Eq_707 * g_ptr413940 = &g_t41398C;
Eq_57 g_t413C30 = 
	{
		4275324
	};
struct Eq_707 * g_ptr416FA4 = &g_t416FF0;
struct Eq_707 * g_ptr417000 = &g_t41704C;
struct Eq_707 * g_ptr4173B4 = &g_t417400;
struct Eq_707 * g_ptr417530 = &g_t41757C;
struct Eq_707 * g_ptr417630 = &g_t41767C;
struct Eq_707 * g_ptr4179C0 = &g_t417A0C;
struct Eq_707 * g_ptr417A20 = &g_t417A6C;
Eq_7469 g_t419074 = 
	{
		0x00
	};
byte g_b41910C = 0x09;
byte g_b419160 = 0x01;
byte g_b41919C = 0x0F;
byte g_b41926C = 0x01;
byte g_b4192B8 = 0x01;
byte g_b4192D8 = 0x0F;
byte g_b419334 = 0x0E;
byte g_b419400 = 0x00;
struct Eq_707 * g_ptr41A1BC = &g_t41A208;
Eq_707 g_t41C538 = 
	{
		&g_t224288FC,
		<code>,
		
		{
			0x45
		},
		
		{
			0xFF
		},
		
		{
			0x5B5E
		},
		
		{
			0x5D
		},
		
		{
			0x53
		},
		
		{
			0xC4
		},
		0x738BD88B,
		0x1C7E3B28,
		&g_tFFF2BFE8,
		0x835756FF,
		&g_t7C8D18C6,
		0x15B90824,
		
		{
			0xC3
		},
		0xC3000000,
		0x53,
	};
struct Eq_707 * g_ptr41CD1C = &g_t41CD68;
struct Eq_707 * g_ptr4244B0 = &g_t4244FC;
byte g_b426A58 = 0x2E;
struct Eq_2827 * g_ptr426C08 = &g_t426C0C;
struct Eq_2827 * g_ptr427164 = &g_t427168;
struct Eq_2827 * g_ptr427460 = &g_t427464;
Eq_1089 g_t427844 = 
	{
		58,
		&g_a42784C,
	};
byte g_b427C90 = 0x47;
Eq_2 g_t428000 = 
	{
		0x00
	};
Eq_2 g_t428004 = 
	{
		0x00
	};
<anonymous> * g_ptr42800C = null;
<anonymous> * g_ptr428014 = null;
byte g_b428030 = 0x00;
byte g_b428034 = 0x01;
Eq_2 g_t428038 = 
	{
		0x00
	};
struct Eq_4798 * g_ptr42803C = null;
<anonymous> * g_ptr428040 = &g_t4023D4;
<anonymous> * g_ptr428044 = &g_t402580;
<anonymous> * g_ptr428048 = &g_t40295C;
Eq_2 g_t4280A0 = 
	{
		0x00
	};
Eq_1174 g_t4280A4 = 
	{
		0x00000000,
	};
Eq_2 g_t4280A8 = 
	{
		0x00
	};
word32 g_dw4280AC = 0x00000000;
word32 g_dw4280B0 = 0x00000000;
word32 g_dw42810C = 0x00000000;
word32 g_dw4283AC = 0x00000000;
byte g_b4283B7 = 0x0D;
byte g_b4283D8 = 0x00;
word16 g_a42863C[] = 
	{
	};
struct Eq_7028 * g_ptr428664 = null;
word32 g_dw42A598 = 0x00000117;
word32 g_dw42A59C = 0x000000AF;
word32 g_dw42A5B0 = 0x0000015C;
word32 g_dw42A5B4 = 0x000000AF;
int32 g_dw42A5C8 = 397;
word32 g_dw42A5CC = 0x000000AF;
word32 g_dw42A5D0 = 0x00000117;
word32 g_dw42A5D4 = 0x00000251;
Eq_2 g_t42A67C = 
	{
		0x44
	};
struct Eq_312 * g_ptr42A710 = &g_t42B21C;
Eq_2 g_t42A724 = 
	{
		0x2C
	};
Eq_2 g_t42A734 = 
	{
		0x24
	};
Eq_2 g_t42A754 = 
	{
		0x4C
	};
Eq_2 g_t42A788 = 
	{
		0xD0
	};
byte * g_ptr42A8C0 = &g_b42B04C;
Eq_2 g_t42A8DC = 
	{
		0x34
	};
Eq_2 g_t42A8E0 = 
	{
		0x08
	};
Eq_2 g_t42A8EC = 
	{
		0x54
	};
Eq_2 g_t42A9D4 = 
	{
		0x4C
	};
<anonymous> * g_ptr42B008 = null;
<anonymous> * g_ptr42B014 = null;
word32 g_dw42B018 = 0x00000000;
<anonymous> * g_ptr42B028 = null;
<anonymous> * g_ptr42B02C = null;
word32 g_dw42B030 = 0x00000000;
byte g_b42B038 = 0x00;
<anonymous> * g_ptr42B048 = null;
byte g_b42B04C = 0x00;
Eq_312 g_t42B050 = 
	{
		0x0000,
		
		{
			0x0000
		},
		0x00000000,
		0x00000000,
		0x00000000,
		null,
		null,
		null,
		null,
		0x00,
	};
Eq_312 g_t42B21C = 
	{
		0x0000,
		
		{
			0x0000
		},
		0x00000000,
		0x00000000,
		0x00000000,
		null,
		null,
		null,
		null,
		0x00,
	};
word16 g_w42B220 = 0x0000;
up32 g_dw42B228 = 0x00000000;
<anonymous> * g_ptr42B238 = null;
Eq_312 g_t42B3E8 = 
	{
		0x0000,
		
		{
			0x0000
		},
		0x00000000,
		0x00000000,
		0x00000000,
		null,
		null,
		null,
		null,
		0x00,
	};
word32 * g_a42B638[] = 
	{
	};
struct Eq_1056 * g_ptr42B63C = null;
struct Eq_1089 * g_ptr42B640 = null;
int32 g_dw42B644 = 0;
struct Eq_1174 * g_ptr42B648 = null;
struct Eq_1262 * g_ptr42B650 = null;
byte g_b42B660 = 0x00;
byte g_b42B664 = 0x00;
Eq_2 g_t42B668 = 
	{
		0x00
	};
Eq_2 g_t42B670 = 
	{
		0x00
	};
byte g_b42B750 = 0x00;
Eq_2 g_t42B884 = 
	{
		0x00
	};
word32 g_dw42B88C = 0x00000000;
Eq_2 g_t42B890 = 
	{
		0x00
	};
Eq_2 g_t42B894 = 
	{
		0x00
	};
Eq_2 g_t42B898 = 
	{
		0x00
	};
struct _RTL_CRITICAL_SECTION g_t42B8A0 = 
	{
		null,
		0,
		0,
		null,
		null,
		0x00000000,
	};
struct _RTL_CRITICAL_SECTION g_t42B8B8 = 
	{
		null,
		0,
		0,
		null,
		null,
		0x00000000,
	};
Eq_2 g_t42B8D0 = 
	{
		0x00
	};
Eq_2 g_t42B8D4 = 
	{
		0x00
	};
Eq_2 g_t42B8D8 = 
	{
		0x00
	};
struct Eq_7028 * g_ptr42B8DC = null;
Eq_2 g_t42D3C8 = 
	{
		0x00
	};
Eq_2 g_t42D3CC = 
	{
		0x00
	};
struct Eq_707 * g_ptr42D3D0 = null;
Eq_2674 g_t406B58 = 
	{
		
		{
			0x0E
		},
		0x0A,
	};
Eq_707 g_t4071C4 = 
	{
		&g_t000C,
		<code>,
		
		{
			0x6E
		},
		
		{
			0x74
		},
		
		{
			0x726F
		},
		
		{
			0x20
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		0x00000000,
		0x00000000,
		null,
		0x00000000,
		&g_t407220,
		0x00000010,
		
		{
			0x10
		},
		0x00408D6E,
		0x80,
	};
Eq_707 g_t413450 = 
	{
		&g_t000C,
		<code>,
		
		{
			0x73
		},
		
		{
			0x72
		},
		
		{
			0x34A8
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		0x00000000,
		0x00000000,
		null,
		0x004134A8,
		&g_t000C,
		0x00406B74,
		
		{
			0x10
		},
		0x00413508,
		0x00,
	};
Eq_707 g_t413508 = 
	{
		&g_t0010,
		<code>,
		
		{
			0x74
		},
		
		{
			0x65
		},
		
		{
			0x6372
		},
		
		{
			0x64
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		0x00000000,
		0x00000000,
		null,
		0x00000000,
		&g_t413564,
		0x0000000C,
		
		{
			0x10
		},
		0xC08B6E6F,
		0xC4,
	};
Eq_707 g_t413564 = 
	{
		&g_t000C,
		<code>,
		
		{
			0x76
		},
		
		{
			0x64
		},
		
		{
			0x6172
		},
		
		{
			0x6F
		},
		
		{
			0xC4
		},
		
		{
			0x00
		},
		0x00000000,
		0x00000000,
		null,
		0x00000000,
		null,
		0x004135D4,
		
		{
			0xD4
		},
		0x004142BC,
		0x05,
	};
Eq_707 g_t41398C = 
	{
		&g_t0030,
		<code>,
		
		{
			0x1C
		},
		
		{
			0x14
		},
		
		{
			0x58F0
		},
		
		{
			0x24
		},
		
		{
			0x28
		},
		
		{
			0x2C
		},
		0x00414E00,
		0x00415AA0,
		&g_t415BD0,
		0x004154C0,
		&g_t415BEC,
		0x00415C60,
		
		{
			0xB4
		},
		0x00415140,
		0xEC,
	};
Eq_707 g_t416FF0 = 
	{
		&g_t000C,
		<code>,
		
		{
			0x76
		},
		
		{
			0x64
		},
		
		{
			0x6870
		},
		
		{
			0x4C
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		0x00000000,
		0x00000000,
		null,
		0x00000000,
		&g_t41704C,
		0x0000000C,
		
		{
			0x10
		},
		0x7265704F,
		0x61,
	};
Eq_707 g_t41704C = 
	{
		&g_t000C,
		<code>,
		
		{
			0x76
		},
		
		{
			0x64
		},
		
		{
			0x6870
		},
		
		{
			0x4F
		},
		
		{
			0x61
		},
		
		{
			0x6E
		},
		0x0041706C,
		0x46540A03,
		&g_t68637469,
		0x00000001,
		&g_t0200,
		0x41706800,
		
		{
			0x72
		},
		0x90656D61,
		0xC0,
	};
Eq_707 g_t417400 = 
	{
		&g_t0024,
		<code>,
		
		{
			0x74
		},
		
		{
			0xA4
		},
		
		{
			0x000E
		},
		
		{
			0x00
		},
		
		{
			0x00
		},
		
		{
			0x41
		},
		0x00010000,
		0x8588FFFD,
		&g_t746E6F46,
		0x00417430,
		&g_t46540507,
		0x00746E6F,
		
		{
			0x01
		},
		0x6F8C7465,
		0x41,
	};
Eq_707 g_t41757C = 
	{
		&g_t001C,
		<code>,
		
		{
			0x74
		},
		
		{
			0x80
		},
		
		{
			0x5404
		},
		
		{
			0x6E
		},
		
		{
			0x94
		},
		
		{
			0x07
		},
		0x757C6E65,
		0x73500041,
		&g_t61724708,
		0x63696870,
		&g_t8C000473,
		0xA000416F,
		
		{
			0x00
		},
		0x6F4D0400,
		0x64,
	};
Eq_707 g_t41767C = 
	{
		&g_t0018,
		<code>,
		
		{
			0x74
		},
		
		{
			0x48
		},
		
		{
			0x5406
		},
		
		{
			0x75
		},
		
		{
			0x94
		},
		
		{
			0x07
		},
		0x68737572,
		0x0041767C,
		&g_t47080002,
		0x68706172,
		&g_t2736369,
		0x416F8C00,
		
		{
			0x00
		},
		0x05000100,
		0x53,
	};
Eq_707 g_t417A0C = 
	{
		&g_t0074,
		<code>,
		
		{
			0x0C
		},
		
		{
			0x74
		},
		
		{
			0x6D49
		},
		
		{
			0x65
		},
		
		{
			0x6C
		},
		
		{
			0x00
		},
		0x00000000,
		0x00000000,
		null,
		0x00000000,
		null,
		0x00417ADC,
		
		{
			0xD4
		},
		0x004148BC,
		0x9C,
	};
Eq_707 g_t417A6C = 
	{
		&g_t003C,
		<code>,
		
		{
			0x20
		},
		
		{
			0xC0
		},
		
		{
			0x48BC
		},
		
		{
			0x9C
		},
		
		{
			0xA8
		},
		
		{
			0x6C
		},
		0x0041B55C,
		0x0041B610,
		&g_t41A0B8,
		0x0041B798,
		&g_t41BB84,
		0x0041C2BC,
		
		{
			0x60
		},
		0x0041C184,
		0x07,
	};
Eq_707 g_t41A208 = 
	{
		&g_t0064,
		<code>,
		
		{
			0x74
		},
		
		{
			0x88
		},
		
		{
			0x9418
		},
		
		{
			0x04
		},
		
		{
			0x88
		},
		
		{
			0x0D
		},
		0x70616D74,
		0x766E6143,
		&g_t41A234,
		0x42540D07,
		&g_t616D7469,
		0x6E614370,
		
		{
			0x86
		},
		0x896430FF,
		0x20,
	};
Eq_707 g_t224288FC;
Eq_707 g_tFFF2BFE8;
<anonymous> g_t7C8D18C6;
Eq_707 g_t41CD68 = 
	{
		&g_t0040,
		<code>,
		
		{
			0x20
		},
		
		{
			0xC0
		},
		
		{
			0x48BC
		},
		
		{
			0x9C
		},
		
		{
			0xA8
		},
		
		{
			0x6C
		},
		0x0041B55C,
		0x0041B610,
		&g_t41A0B8,
		0x0041B798,
		&g_t41BB84,
		0x0041C2BC,
		
		{
			0x60
		},
		0x0041C184,
		0x09,
	};
Eq_707 g_t4244FC = 
	{
		&g_t000C,
		<code>,
		
		{
			0x6C
		},
		
		{
			0x69
		},
		
		{
			0x7272
		},
		
		{
			0x24
		},
		
		{
			0x3A
		},
		
		{
			0x74
		},
		0x636A2F2F,
		0x76732E6C,
		&g_t65637275,
		0x67726F66,
		&g_t656E2E65,
		0x76732F74,
		
		{
			0x2F
		},
		0x74536C63,
		0x72,
	};
Eq_2827 g_t426C0C = 
	{
		
		{
			0x11
		},
		0x02,
		
		{
		},
	};
Eq_2827 g_t427168 = 
	{
		
		{
			0x11
		},
		0x02,
		
		{
		},
	};
Eq_2827 g_t427464 = 
	{
		
		{
			0x11
		},
		0x02,
		
		{
		},
	};
Eq_19683 g_a42784C[] = 
	{
	};
<anonymous> g_t4023D4 = <code>;
<anonymous> g_t402580 = <code>;
<anonymous> g_t40295C = <code>;
Eq_707 g_t000C;
<anonymous> g_t407220 = <code>;
Eq_707 g_t0010;
Eq_707 g_t0030;
Eq_707 g_t415BD0 = 
	{
		&g_t753BB77D,
		<code>,
		
		{
			0x8B
		},
		
		{
			0xC1
		},
		
		{
			0x1043
		},
		
		{
			0xCE
		},
		
		{
			0x73
		},
		
		{
			0xC3
		},
		0x0974D284,
		0x92FF108B,
		&g_tFF108BC3,
		0x00008092,
		&g_tC08BC300,
		0x10588B53,
		
		{
			0x53
		},
		0x92FF108B,
		0x84,
	};
<anonymous> g_t415BEC = <code>;
Eq_707 g_t68637469;
<anonymous> g_t0200;
Eq_707 g_t0024;
Eq_707 g_t746E6F46;
<anonymous> g_t46540507;
Eq_707 g_t001C;
Eq_707 g_t61724708;
<anonymous> g_t8C000473;
Eq_707 g_t0018;
Eq_707 g_t47080002;
<anonymous> g_t2736369;
Eq_707 g_t0074;
Eq_707 g_t003C;
Eq_707 g_t41A0B8 = 
	{
		&g_t89645959,
		<code>,
		
		{
			0x55
		},
		
		{
			0x56
		},
		
		{
			0x8B20
		},
		
		{
			0x40
		},
		
		{
			0xB2
		},
		
		{
			0xBF
		},
		0xC033FC45,
		0xA1046855,
		&g_t20896430,
		0x8BFC558B,
		&g_tFF088BC6,
		0xC0335451,
		
		{
			0x55
		},
		0x8B530C5D,
		0x5D,
	};
<anonymous> g_t41BB84 = <code>;
Eq_707 g_t0064;
Eq_707 g_t41A234 = 
	{
		&g_t414774,
		<code>,
		
		{
			0x69
		},
		
		{
			0x70
		},
		
		{
			0x6176
		},
		
		{
			0xA2
		},
		
		{
			0x77
		},
		
		{
			0x00
		},
		0x69687061,
		0x00007363,
		&g_t64A1F4C4,
		0xE8004286,
		&g_tFFFFA384,
		0x33F84589,
		
		{
			0x45
		},
		0xC0333374,
		0x55,
	};
<anonymous> g_t616D7469;
Eq_707 g_t0040;
Eq_707 g_t65637275;
<anonymous> g_t656E2E65;
Eq_707 g_t753BB77D;
Eq_707 g_tFF108BC3;
<anonymous> g_tC08BC300;
Eq_707 g_t89645959;
Eq_707 g_t20896430;
<anonymous> g_tFF088BC6;
Eq_707 g_t414774 = 
	{
		&g_tFEFAEFE8,
		<code>,
		
		{
			0x55
		},
		
		{
			0xC4
		},
		
		{
			0x53FF
		},
		
		{
			0x33
		},
		
		{
			0xFC
		},
		
		{
			0xD8
		},
		0x41480D68,
		0x30FF6400,
		&g_tFFFEFC95,
		0xE8038BFF,
		&g_tFFFEEEF0,
		0xFEFC958D,
		
		{
			0xF1
		},
		0xFC75FF16,
		0x68,
	};
Eq_707 g_t64A1F4C4;
<anonymous> g_tFFFFA384;
Eq_707 g_tFEFAEFE8;
Eq_707 g_tFFFEFC95;
<anonymous> g_tFFFEEEF0;

